### ISSUE TITLE
run_737800 is not fully relaxed at its final solution

### ISSUE THREAD

**Issue by bqpd** [hoburg/SPaircraft#100]
@mayork, @1ozturkbe 

```
...
               | Mission/Aircraft/Fuselage/Relax
      C_{fuse} : 1                         Fuselage Weight Margin and Sensitivity
      N_{land} : 1                         Emergency landing load factor
      R_{fuse} : 1.082                     Fuselage radius
           SPR : 1                         Number of seats per row
   W''_{floor} : 1                         Floor weight/area density
...
```

and in general (as I'm sure you know) this solution is balanced on a knife-edge.

You may not know, though, that it gets a >100% better (and equally relaxed) solution with a relaxed-vars power of 10 instead of 20; I haven't checked if the solution is ridiculous.

**Comment by 1ozturkbe** [comment]
hmm, we haven't run run_737800 in many months... :P Can you run run_optimal_737 instead, and see what you get?

**Comment by bqpd** [comment]
you guys set it up as the test...

**Comment by bqpd** [comment]
I'll do a quick check, but in general y'all need to update the tests; this is the whole reason the faster solves haven't been merged yet.

**Comment by 1ozturkbe** [comment]
we are really silly @bqpd, our b. Will fix ASAP.

**Comment by bqpd** [comment]
what arguments should I use for `run_optimal_737` ? I'm on master

**Comment by 1ozturkbe** [comment]
it should be ('W_{f_{total}}', True, False).

**Comment by mayork** [comment]
@bqpd we've been running on the `spajoa_edits` branch for a while. I have the tests working there. I'll merge it right now and that will resolve any issues.

**Comment by bqpd** [comment]
tests are working on gpkit/master, to be clear, but on nomialmaps numerical issues push it to fail occassionally

**Comment by mayork** [comment]
alright @bqpd everything should be resolved on master now. The test is the optimal 737 run. I'm going to close this but feel free to reopen if you discover something is still messed up.

**Comment by bqpd** [comment]
Great, thanks!

**Comment by mayork** [comment]
@bqpd I've been running on nomial maps and haven't seen any issues with the test file. It has never once failed for me.

**Comment by bqpd** [comment]
Phew. It's passing here...trying Jenkins now. Hopefully this was just a run_737800 issue

**Comment by 1ozturkbe** [comment]
yeah, and the issue with run_737800 is the Rfuse sub. Could have resolved it that way too @mayork, but I don't think we will be using that model in the short term anyways.
