### ISSUE TITLE
Removing the multimission distinction 

### ISSUE THREAD

**Issue by 1ozturkbe** [hoburg/SPaircraft#43]
Oh btw @mayork we should just not have a multimission distinction. You should just specify your mission right before building the model. We don't have to do this right away, but it doesn't make sense to have the distinction if you can just run with Nmission = 1.  I think it would make it much more intuitive, and help us avoid the explosion in booleans; what do you think?

**Comment by 1ozturkbe** [comment]
Obviously though, we have to fix issue 42 first :P

**Comment by mayork** [comment]
I agree 100%, i tried that initially but theres #37 which made that not an attractive option

**Comment by mayork** [comment]
so in order to keep #40 from being a problem we need #37 fixed then we can fix this issue

**Comment by 1ozturkbe** [comment]
Glad we are on the same page!

**Comment by mayork** [comment]
took a stab at this today...uncovered numerous issues

**Comment by mayork** [comment]
@1ozturkbe this has been completed. Closing.
