### ISSUE TITLE
Multi-mission does not solve reliably

### ISSUE THREAD

**Issue by mayork** [hoburg/SPaircraft#47]
Could we be pushing the bounds of Mosek? The problem is 5,299 variables

**Comment by mayork** [comment]
solve stability seems to decrease as Nmission is increased...are we pushing the bounds of Mosek?

**Comment by 1ozturkbe** [comment]
It is very possible. I was reading [this](http://blog.mosek.com/2014/06/what-if-solver-stall.html) from a Mosek blog, and it seems that the NEAR_OPTIMAL is an indicator that the solver is stalling/not making meaningful progress towards a solution. And we start getting NEAR_OPTIMAL's even with 1700 variables...

**Comment by mayork** [comment]
It might be worth considering doing some variable normalizations to make everything of roughly the same order of magnitude

**Comment by 1ozturkbe** [comment]
I think good initial guesses are probably more if not just as important, especially since the near_optimals occur (at least for me) near the beginning of a solve. Is there a way to nicely convert a solution to an x0?

**Comment by mayork** [comment]
pass in x0=sol

**Comment by 1ozturkbe** [comment]
But for the multimission, not for the single one... :P

**Comment by mayork** [comment]
have to iterate over the single mission solution and turn everything that is vetorized into a vector then store it all in a dict and pass that in for x0

**Comment by 1ozturkbe** [comment]
Btw, the multimission runs fine now, but I'm getting that all of the weights are the same for the aircraft for different n_pax. Is it possible something isn't vectorized properly?

**Comment by mayork** [comment]
by all the weights, what do you mean specifically. all that should be changing is the weight from passengers and fuel burn

**Comment by mayork** [comment]
and it doesn't run fine if you increase Nmission to 4 it gets sketchy

**Comment by 1ozturkbe** [comment]
Since we have resolved the NEAR_OPTIMAL issue, I think the multimission is much more well-behaved. Closing this. Instead, we should focus on issue #82, which still messes with my head.
