### ISSUE TITLE
why is everything wrapped in BCS?

### ISSUE THREAD

**Issue by mayork** [hoburg/SPaircraft#51]

**Comment by 1ozturkbe** [comment]
Because the codes will not converge without it, even though there are zero variables hitting the bounds. Still under investigation...

**Comment by 1ozturkbe** [comment]
This is related to issue 52, and when that gets resolved should be a non-issue. Allowing lower reltol allowed for the removal of BCS. Will keep this open so that we make sure to remove Bounded.

**Comment by 1ozturkbe** [comment]
Another reminder to keep this in the foreground...

**Comment by 1ozturkbe** [comment]
@mayork I don't like that we still use BCS, but this is only because we have sizing constraints (like climb time, climb distance, VT yaw rate) that are sometimes not active. Should we close, since we will likely never be able to get rid of BCS?

**Comment by mayork** [comment]
yes close...if you look at the output all that is at the bounds is either inactive tail sizing constraints or other inactive variables (like min cruise altitude if that isn't subbed in).

I'm closing now.
