### ISSUE TITLE
New Repo Name

### ISSUE THREAD

**Issue by mayork** [hoburg/SPaircraft#60]
We can do a lot more than model a D8 with this code, I'd like to change the repo name and all of our main file names to reflect his for marketing reasons.

@1ozturkbe, @mjburton11, @bqpd any ideas?

**Comment by 1ozturkbe** [comment]
Good idea. How about SPAC (SP aircraft), or some derivative? Or SigTAC
(Signomial transport aircraft)? ACS (Aircraft system) or some derivative?
We could also throw fast/rapid in there. Just spitballing...

**Comment by bqpd** [comment]
Or would it make sense to move the generic parts to gpkit-models?

**Comment by mayork** [comment]
the whole thing is pretty generic, there's prob less than 300 lines of code specific to any one aircraft configuration in `D8.py` and the substitution files for each aircraft

**Comment by 1ozturkbe** [comment]
I personally would rather not split the models, because a designer may need to access one of the submodels to be able to design a certain aircraft (eg. depending on the tail configuration, the tail sizing constraints might be in the tail files or in aircraft). It would make more sense to let it be 'monolithic'.

**Comment by bqpd** [comment]
(in person, discussed moving the parts of this that were updates of Philipe's thesis to gpkit-models and keeping the rest in a separate repository linked to from the gpkit-models)

**Comment by mayork** [comment]
also ideally write a unit test for each file and put that into gpkit models

**Comment by bqpd** [comment]
in a perfect world, even a README with a graph :o

**Comment by 1ozturkbe** [comment]
... but have we decided on a name? Let's try and figure this out by the end of the week!

**Comment by 1ozturkbe** [comment]
I'm also happy just calling it SPaircraft. It just should be called something other than d8.

**Comment by mayork** [comment]
Signomial Transport Aircraft Conceptual Design?

**Comment by 1ozturkbe** [comment]
That is a horrendous acronym lol.

**Comment by mayork** [comment]
I don't think it's that bad, STACD pronounced like "stacked"

**Comment by 1ozturkbe** [comment]
actually, i didn't even realize. That is pretty awesome! objections?

**Comment by mayork** [comment]
@whoburg thoughts before we change the name?

**Comment by mayork** [comment]
woody said he was fine with whatever but suggested it be signomial programming ___________

**Comment by 1ozturkbe** [comment]
I guess STACD has signomial in it... does that cut it?

**Comment by 1ozturkbe** [comment]
bump!

**Comment by bqpd** [comment]
(up to you guys and @whoburg, I'm not one of the people who has to find the name intuitive :p)

**Comment by 1ozturkbe** [comment]
It seems like @whoburg does not feel strongly about this issue. I will change the name. Closing.

**Comment by 1ozturkbe** [comment]
It turns out I cannot do this, since I do not have access to the repo settings. @bqpd @whoburg @mayork can one of you take care of this?

**Comment by mayork** [comment]
How do you do it?

**Comment by 1ozturkbe** [comment]
You are supposed to be able to click the + icon at the top, and see settings for the repo. But I guess neither of us can do this.

**Comment by mayork** [comment]
Yep I don’t appear to have access

**Comment by whoburg** [comment]
STACD is a pretty horrible name.

SPaircraft is fine, or maybe just TASOPT-SP or SP-TASOPT?

**Comment by 1ozturkbe** [comment]
Yey! Glad to hear your opinion. 
I personally am fine going ahead with SPaircraft, or SPAC as I had originally proposed, but think that the names that incorporate TASOPT are a mouthful. @mayork, what are your feelings?

**Comment by 1ozturkbe** [comment]
@mayork let's get a decision on this. Especially important since I have made some progress on [documentation](http://hoburgd8.readthedocs.io/en/docs/). Isn't that cool?

**Comment by 1ozturkbe** [comment]
@whoburg can you give Martin and I admin permissions for hoburg/d8? And also, can we change the repo name to  SPaircraft?

**Comment by bqpd** [comment]
(admin permissions given)

**Comment by mayork** [comment]
I think we go SPaircraft

**Comment by mayork** [comment]
Eventually there may be a GPaircraft repo

**Comment by 1ozturkbe** [comment]
I think we are done here. Closing.

**Comment by bqpd** [comment]
(the readme still says D8)

**Comment by 1ozturkbe** [comment]
Was literally changing it right now.

**Comment by bqpd** [comment]
haha!

**Comment by whoburg** [comment]
new name seems good to me
