### ISSUE TITLE
CG Model/Fuselage Pitching Model

### ISSUE THREAD

**Issue by mayork** [hoburg/SPaircraft#62]
For now this is just a discussion...

Berk I noticed that when running `run_M072_737() ` and `run_D8_eng_wing_opt()` the HT of the 737 weight only 260 pounds while the D8 HT is about 900 pounds.

I found this very odd and think it could be due to either how we lump the CG calculation or perhaps fuselage pitching moment. 

@1ozturkbe can you elaborate on how we handle fuselage pitching moment as well as how the CG is lumped?

**Comment by 1ozturkbe** [comment]
I'd be very suspicious of saying it's because of lumping. I will take a look now and post updates here.

**Comment by 1ozturkbe** [comment]
Btw, can you make a note every time you add a new aircraft model? It's really hard for me to keep track of the VSP stuff if in every pull there is a new model I don't know about.

**Comment by 1ozturkbe** [comment]
Just so you know btw, I am working on the readthedocs branch (I messed up, and forgot to change over before making changes. ) Will let you know when I have something concrete.

**Comment by 1ozturkbe** [comment]
D8_eng_wing is soooo wonky... It pretends like it as a 73 fuselage. That's the first issue... I will fix and let you know.

**Comment by 1ozturkbe** [comment]
(this is exactly why you should get VSP working. you would have seen the issues right away :P)

**Comment by 1ozturkbe** [comment]
I looked through the documentation and found the pitching moment relations. Added a template CM  variable to D8_fuselage, but this is pending MTFLOW results.

**Comment by 1ozturkbe** [comment]
@mayork just wanted to point you to this issue, so we can convince ourselves that the HTs were light to begin with...

**Comment by mayork** [comment]
i agree they always were light

**Comment by mayork** [comment]
CG model seems good. I'm closing. @1ozturkbe reel free to reopen if you see fit.
