### ISSUE TITLE
Morphing Chart Explanations

### ISSUE THREAD

**Issue by mayork** [hoburg/SPaircraft#72]
@1ozturkbe can you dig into the 777 and RJ morphing plots and start explaining why they look how they do? The sensitivity plots should be very useful. I also think there's something to do with the structural efficiency of the original fuselage since everything is being pressurized to the same level

**Comment by 1ozturkbe** [comment]
I know what I'm doing on the plane today!

**Comment by mayork** [comment]
@1ozturkbe i want to focus on these six charts:

[D8_standard_killer_chart.pdf](https://github.com/hoburg/d8/files/1016350/D8_standard_killer_chart.pdf)
[RJ_standard_killer_chart.pdf](https://github.com/hoburg/d8/files/1016351/RJ_standard_killer_chart.pdf)
[RJ_M08_standard_killer_chart.pdf](https://github.com/hoburg/d8/files/1016352/RJ_M08_standard_killer_chart.pdf)
[D8_M08_morphing_chart_fixed_BPR.pdf](https://github.com/hoburg/d8/files/1016353/D8_M08_morphing_chart_fixed_BPR.pdf)
[D8_777_morphing_chart_.pdf](https://github.com/hoburg/d8/files/1016354/D8_777_morphing_chart_.pdf)
[D8_777_morphing_chart_reordered.pdf](https://github.com/hoburg/d8/files/1016355/D8_777_morphing_chart_reordered.pdf)


I think a good first step is to VSP every step and make sure everything there makes sense. Also need to analyze the sensitivity charts. Hopefully that will lead to a satisfactory explanation of everything. We really need to figure out the deal with #73 cause that is really effecting how the step to D8 fuselage looks on some of these plots...

I've been spending a solid 50+ hours a week on D8 this month but that's going to have to really drop off after Wednesday so it'd be great if you could pick up some slack

**Comment by 1ozturkbe** [comment]
You've been an absolute champion this month, seriously. I really appreciate it. But HOLY MOSES we have so much to do! I totally blanked on the volume of stuff since I have been so busy first with the JHO paper and then with robustSP. Woooooow. Will do my best.

**Comment by 1ozturkbe** [comment]
I have put a bunch of updates to the code with the purpose of streamlining the process of analysing the charts. This way we make sure that all plots are alphabetically sorted. My aim is to get all of the VSPs ready by tomorrow night, and have explanations for all of the interesting observations by the night of the 23rd.

**Comment by 1ozturkbe** [comment]
I think there were some pretty severe (tail) modeling errors that were causing the discrepancies in the morphing charts. I am in the process of fixing them. Once the percent_diffs start looking better, I will reopen this.
