### ISSUE TITLE
Morphing chart VT sizing

### ISSUE THREAD

**Issue by mayork** [hoburg/SPaircraft#73]
If you run the standard TASOPT morphing chart recreation and specify 0.03 as the min VT volume for all aircraft we get a pretty different looking plot. You have to specify a min VT volume of 0.1 for the 737 and M=0.72 737. We need to figure out if this is what TASOPT is doing in that plot or not because I don't really like our result, seems like it shouldn't depend so much on what we specify the min VT volume to be. @1ozturkbe what are your thoughts on this.

**Comment by 1ozturkbe** [comment]
I think we can close this, since we agree that our 2 VT sizing constraints make much more reliable VTs than a simple VT volume coefficient. Closing; feel free to reopen @mayork if you disagree.
