### ISSUE TITLE
M 0.72 cruise 737 overly sensitive to min tail volume

### ISSUE THREAD

**Issue by mayork** [hoburg/SPaircraft#74]
@1ozturkbe this really worries me. The difference between a min VT volume of .1 and .03 is gigantic. I can't explain it.

**Comment by 1ozturkbe** [comment]
I see it... I can't justify setting a min tail volume of 0.1 when 0.042 seems to be optimal though. Don't really know the way forward with this.

**Comment by mayork** [comment]
I figured it out...had to do with fuselage drag mdoel. we really need a bigger one.

**Comment by 1ozturkbe** [comment]
bigger tail? Why is it so?

**Comment by mayork** [comment]
I just ran a TASOPT 737 and set the fuselage lift percent and drag coefficient ti what thatvoutput and generated this plot. I put tail volume to .05, the optimal for the Mach 0.8 case

**Comment by 1ozturkbe** [comment]
I am really confused about this issue. What is the status on this @mayork? Can we close?

**Comment by mayork** [comment]
yeah i think so
