### ISSUE TITLE
June 13 commits result in large model errors

### ISSUE THREAD

**Issue by mayork** [hoburg/SPaircraft#83]
@1ozturkbe after I pulled and merged I'm getting fuel burn errors >>100%...I reverted to https://github.com/hoburg/d8/commit/d44a411e4976a65986c5df1ca6ac6258299c5e48 and everything works fine. I think something happened in the 13 June series of commits

**Comment by mayork** [comment]
reverting also resolved that issue with the 777 validation case

**Comment by 1ozturkbe** [comment]
That is so odd... everything working perfectly for me.

**Comment by 1ozturkbe** [comment]
Ran it again, and I'm only getting 2% error in fuel burn for D8. Are you sure about this? Mind you, I haven't merged the June 19th commits; I'm a little confused as to why some of the subs have changed.

**Comment by mayork** [comment]
Merge the June 19th and see what happens?

**Comment by 1ozturkbe** [comment]
Still works? Odd.

**Comment by 1ozturkbe** [comment]
@mayork let me know when you run it next. But I know you are on vacation, so no pressure.

**Comment by 1ozturkbe** [comment]
@mayork bump. Would like to make sure you can run everything reliably.

**Comment by mayork** [comment]
looks like i can run everything reliably right now

**Comment by 1ozturkbe** [comment]
Excellente! Closing.
