### ISSUE TITLE
Some arbitrary constraints pushing the model, oops. 

### ISSUE THREAD

**Issue by 1ozturkbe** [hoburg/SPaircraft#84]
Hey @mayork, I noticed this constraint today within D8:
```python
CruiseAlt >= 35000. * units('ft'),
```
Oops. Putting this here as a reminder to scrub the entire model for constraints like these, because I'm pretty certain this was pushing both 737 and D8 (altitude was lower-bounded).

**Comment by mayork** [comment]
not an oops....TASOPT requires cruise alt to start there so I was enforcing that. To get a realistic design we need a constraint like that because we have ot have the capability to fly at that kind of cruise altitude

**Comment by 1ozturkbe** [comment]
We definitely should not set this, and the model works fine without it. It is totally arbitrary; I don't see why 35000ft is better than 30000ft. The D8 and M072_737 want to fly low and slow, so we should let them.

**Comment by 1ozturkbe** [comment]
I remember why we decided to set this, but now I'm backing out on that decision. I think it is a bad idea. Instead I think we should constrain the flight time to cruise altitude or the distance to cruise altitude.

**Comment by mayork** [comment]
I see what you're saying but I think it's really more of a capability thing...any realistic aircraft is going to have to be able to fly in the upper 30,000s...one option is to set a singly constraint that like rate of climb at x altitude is greater than some value we choose and then let cruise altitude be totally optimized

**Comment by 1ozturkbe** [comment]
Actually, to give a better idea, here's the first cruise segment altitude for the std_killer_chart. 
[D8_standard_morphing_chart_CruiseAlt.pdf](https://github.com/hoburg/SPaircraft/files/1095368/D8_standard_morphing_chart_CruiseAlt.pdf)

**Comment by 1ozturkbe** [comment]
I should have also plotted the final altitude. Give me a sec.

**Comment by 1ozturkbe** [comment]
So I had actually added a top of climb minimum climb gradient to D8 from TASOPT, so I think we should be good. I just don't want a minimum cruise altitude to skew results.

**Comment by 1ozturkbe** [comment]
I've reduced the altitude to 25,000 ft, just so we can accommodate the M0.72 73 flying just under 30kft. Otherwise, the lower bound in no way influences the results. Closing.
