### ISSUE TITLE
Weight increase from M07_737 to D8_eng_wing +heavy VTs (>200% off) in optimal_D8

### ISSUE THREAD

**Issue by 1ozturkbe** [hoburg/SPaircraft#86]
Investigating...

**Comment by mayork** [comment]
I think this coile be related to the other issue about June 13...check the commits right before 13 June

**Comment by 1ozturkbe** [comment]
Nothing seems out of the ordinary about those commits. All I did about the VT was to rename TASOPT_VT to be D8_VT, and removed the old D8_VT. Will need to dig still.

**Comment by mayork** [comment]
Did i screw up the merge? It wouldn't be the first time...😬

**Comment by 1ozturkbe** [comment]
Seems like this is (at least) part of the issue. Found some rogue subs in optimal_D8. Will fix.

**Comment by 1ozturkbe** [comment]
Even after fixing some rogue subs, we are still around 200% off on VT weight. Will be posting updates here on debugging this.

**Comment by 1ozturkbe** [comment]
<img width="958" alt="vspcompare" src="https://user-images.githubusercontent.com/15684191/27698571-83687386-5cc5-11e7-9129-0068332f234f.PNG">
Adding VSP comparison.

**Comment by 1ozturkbe** [comment]
Part of this also has to do with issue #88. Again, work in progress...

**Comment by 1ozturkbe** [comment]
God... one of the reasons we had an issue is because of a bug we had while reordering constraints... Good thing I'm doing #89 .

**Comment by 1ozturkbe** [comment]
With the fixes I have made, we are still quite heavy (~100%). I am going to investigate this along with the HT lightness issues

**Comment by 1ozturkbe** [comment]
Woooow, I think I know... it is because there is no load factor for the tails; they are just designed for max loads at Vne, duuuuh. So Nlift = 1. Let me see what this does.

**Comment by 1ozturkbe** [comment]
Also, the aspect ratio stuff is off on the VT... can't believe we have made this many mistakes in this.

**Comment by mayork** [comment]
I don't think VT AR is a mistake. Our low fidelity aero model coupled with our structural model pushes the AR unrealistically low so I've had all the files set up to solve with a min VT AR

**Comment by 1ozturkbe** [comment]
The VT is fine now, it's the HT that is not. Will wrap all of this up shortly.

**Comment by 1ozturkbe** [comment]
Alright, the HT's are coming out low in weight because they have tiny aspect ratios. Big root chords are allowing the HT's to be really lightweight. Otherwise the structural models are sound, and the VTs are all on point.

**Comment by mayork** [comment]
HT used to work fine with a free AR. Could it be from the new structural model?

**Comment by 1ozturkbe** [comment]
I'm closing this, because I think we understand and accept that the both tail surfaces are going to be light.
