### ISSUE TITLE
Latex outputs of turbofan need cleaning. 

### ISSUE THREAD

**Issue by 1ozturkbe** [hoburg/SPaircraft#87]
@mayork when I printed sol.table(latex = 2) for any of the SPaircraft, I realized that the variable naming was not very good, usually due to the inconsistent use of brackets {}. I am scrubbing the code once again to make sure that the latex has the absolute minimum processing needed, but I need your help for stuff in hoburg/turbofan (I don't want to mess anything up). I will post the problematic variables here, and perhaps you can clean up both turbofan and make the necessary changes in SPaircraft.

**Comment by 1ozturkbe** [comment]
Problematic names:
- HTR_{f_SUB} : likely should be HTR_{f_{SUB}}, but would be nicer if it only have one letter that is not subscripted. 
- Similarly HTR_{lpc_SUB}

**Comment by 1ozturkbe** [comment]
I have scrubbed the variables in the rest of the models; only engine variables left.

**Comment by mayork** [comment]
I scrubbed everything and found additional items (no guarantees it's a 100% fix but it's close). It's all fixed by commit https://github.com/hoburg/turbofan/commit/481777b98d186dce1aefc5354a3fdd3236d06b44. Closing this issue for now.

@1ozturkbe remember to pull turbofan

**Comment by mayork** [comment]
@1ozturkbe  one thing to note is that i didn't update any subs in this repo. I can do that to a could of the main files. Want it in a PR or straight onto master?

**Comment by 1ozturkbe** [comment]
Ooooooh, if you could update subs too that would be great. straight onto master please.

**Comment by mayork** [comment]
i updated optimal 737 and D8 as well as the 3 analysis cases. that's all I had time to do right now but I think those are the most important files.

**Comment by 1ozturkbe** [comment]
K. I will not be able to merge the HT update until the rest are done. Are you doing this manually?

**Comment by mayork** [comment]
Yeah but it takes like 5 seconds per file...very little in the subs was changed

**Comment by 1ozturkbe** [comment]
K good to know. Pycharm eats through changes like that, so I didn't want you to waste your time.
