### ISSUE TITLE
Pi-tail HT structural model not up to snuff

### ISSUE THREAD

**Issue by 1ozturkbe** [hoburg/SPaircraft#88]
I did some digging (and drew some moment and shear diagrams) and realized that we may be getting wonky HT weight results. I will be making modifications to the structural model soon.

**Comment by 1ozturkbe** [comment]
As a resource, I have been using [this](https://bendingmomentdiagram.com/solve/) to generate my diagrams. It is awesome.

**Comment by 1ozturkbe** [comment]
Sample load distribution, assuming that the lift per unit span is proportional to local chord: 
<img width="342" alt="samplebending" src="https://user-images.githubusercontent.com/15684191/27700164-c03bae04-5cca-11e7-803f-810f2aca81cf.PNG">
<img width="329" alt="samplefbd" src="https://user-images.githubusercontent.com/15684191/27700163-c03867bc-5cca-11e7-8fe3-dce7b9791669.PNG">
<img width="341" alt="sampleshear" src="https://user-images.githubusercontent.com/15684191/27700165-c03c14de-5cca-11e7-8f98-0427b40f6f30.PNG">

**Comment by 1ozturkbe** [comment]
I will need to add a few variables to the model to be able to more accurately model this. It is very straightforward to model max shear, but the moment will require some work.

**Comment by 1ozturkbe** [comment]
It turns out that these calculations are quite involved. Will be working on it over the next few days.

**Comment by 1ozturkbe** [comment]
Will implement issue 89 before I proceed further on this thread...

**Comment by 1ozturkbe** [comment]
This is evolving in the HTstruct branch, but I am getting some underpredictions for the weight with the new model. Investigating.

**Comment by 1ozturkbe** [comment]
At least the low HT weight is uniform across the board, so I think it just has to do with some scaling factor.

**Comment by 1ozturkbe** [comment]
Hmmm, I think we were underestimating the HT weights to begin with. I compared the results of the new model and the old model for the b737 (expecting there to be no difference), and the difference really was due to numerical precision. It turns out we were always low on HT. Is that possible @mayork and we just didn't notice?

**Comment by mayork** [comment]
yes I think we were

**Comment by 1ozturkbe** [comment]
Darn, this is problematic... The new HT structural model I wrote comes within -30% of D8 predictions, and I'm pretty certain it is conservative. But it is more than 80% off on 737...

**Comment by 1ozturkbe** [comment]
I will do my best to figure out why. It may be we are under on D8 because we aren't accounting for panel weights, and that would equivalently help with 73 a little. but there is something fundamentally wrong with the 73 sizing atm.

**Comment by 1ozturkbe** [comment]
Hmm some weird numerical things going on, variables not being pushed properly. Thinking of adding more surrogate variables, and hoping to figure this out soon.

**Comment by 1ozturkbe** [comment]
As of commit 9c7e9472 the new piHT structural model is good. However,we are still under on conventional HT weights. No clue why. Will look into this in another issue.
