### ISSUE TITLE
tests fail sporadically

### ISSUE THREAD

**Issue by whoburg** [hoburg/SPaircraft#91]
Tests are currently failing, e.g.

 - https://acdl.mit.edu/csi/job/gpkit_ResearchModel_d8_Push/
 - https://acdl.mit.edu/csi/job/gpkit_PullRequest_Models/144/

Can @1ozturkbe and @mayork please make it a priority to get these passing?

**Comment by 1ozturkbe** [comment]
Also, I'm not sure why this is, but those tests haven't been run in the last 12 days? How does one build?

**Comment by mayork** [comment]
@1ozturkbe i think we get a master that passes tests and then adjust the settings on this repo so it's like master in the fact someone has to approve all merges to master once tests are passing.

**Comment by 1ozturkbe** [comment]
wait, is it possible that the tests aren't running because the repo name has changed? I would not be surprised, because usually pushes and pull requests should trigger jenkins.

**Comment by mayork** [comment]
@bqpd can you take a look at this? I made a number of pushes to this repo's master two days ago that didn't trigger any tests.

**Comment by bqpd** [comment]
sure thing!

**Comment by bqpd** [comment]
@galbramc, is https://acdl.mit.edu/csi/job/gpkit_ResearchModel_d8_Push/ no longer working with push triggers because the repository was renamed?

**Comment by galbramc** [comment]
yeah the rename would mess things up. I'll rename things in jenkins as well.

**Comment by galbramc** [comment]
test this please

**Comment by galbramc** [comment]
test this please

**Comment by galbramc** [comment]
test this please

**Comment by galbramc** [comment]
duh, this is an issue not a PR... jenkins wont test this...

**Comment by galbramc** [comment]
I think it is all fixed now, but I don't have a PR to test with.

**Comment by mayork** [comment]
I just pushed and the build is passing now so i'm going to close. @galbramc  and @bqpd thanks for your help!
