### ISSUE TITLE
Observed factor of 2 slow down

### ISSUE THREAD

**Issue by mayork** [hoburg/SPaircraft#99]
@bqpd thoughts?

**Comment by bqpd** [comment]
@alisaab is having a similar issue, and it's confusing the heck out of me. You didn't update MOSEK and have checked it wasn't a gpkit commit?

**Comment by mayork** [comment]
@bqpd I updated my mosek license...my previous one expired

**Comment by mayork** [comment]
this is somewhat urgent because @1ozturkbe and I are planning to submit the full system paper between sunday and tuesday.

I know Berk also updated his Mosek license recently.

@bqpd how fast does the model on spajoa_edits solve for you?

To run just do this

```python
from SP_aircraft import run_optimal_737
sol = run_optimal_737('W_{f_{total}}', True, False)
```

**Comment by mayork** [comment]
also @bqpd yes I did checkout out old versions of all the code and the slow down was still there

**Comment by mayork** [comment]
for what it's worth I really think this is a slowdown in the actual GP solve, not model building.

**Comment by mayork** [comment]
@bqpd A single GP solve takes 0.66-0.89 seconds

@1ozturkbe thoughts?

**Comment by bqpd** [comment]
@mayork, even if it's solving `x >= 1` ? Does it take that long for both mosek and mosek_cli?

**Comment by mayork** [comment]
@bqpd no that's how long it is taking to solve the aircraft model. It takes 0.0265 seconds to solve x>=1...I have old timing data in my paper draft though so I know there's a massive slow down.

**Comment by bqpd** [comment]
The code above takes 22 seconds for me, individual solves between 0.25 and 1 second

**Comment by bqpd** [comment]
Running it again in the same prompt, it takes 22.9 seconds, which is consistent. (this and the previous timing are on gpkit:master)

**Comment by bqpd** [comment]
7.76 seconds on gpkit:nomialmap...

**Comment by mayork** [comment]
damn...i thought the fastest branch was master (i.e. nomial map was merged). I think that might have been the issue for me lol...I'll redo the whole timing analysis in a bit but I think it should be the same.

@1ozturkbe

**Comment by mayork** [comment]
This was resolved by switching to the nomialmap branch of gpkit. Closing now.
